version: '2.1'

services:
# Install postgres and setup the database.
  postgres:
    image: debezium/postgres:11
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
# Adminer UI
  adminer:
    image: adminer:4.7.4-standalone
    ports:
      - '9090:8080'
    links:
      - postgres
  
# Install zookeeper. 
  zookeeper:
    image: debezium/zookeeper:0.10
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'

# Install kafka and create needed topics. 
  kafka:
    image: debezium/kafka:0.10 
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250
  debezium-connect:
    image: debezium/connect:0.10
    ports:
      - '8083:8083'
    links:
      - kafka
      - postgres  
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_config
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_status
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false

# Kafka UI
  kafdrop:
    image: obsidiandynamics/kafdrop:3.14.0
    ports:
      - '9000:9000'
    links:
      - kafka
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - SERVER_SERVLET_CONTEXTPATH=/

# Adviser Service
  adviser-service:
    image: lordofthejars/adviser:1.0.0
    ports:
      - '8082:8080'
    links:
      - kafka