version: '2.1'

services:
# Install postgres and setup the database.
  postgres:
    image: debezium/postgres:11
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
  
# Install zookeeper. 
  zookeeper:
    image: debezium/zookeeper:0.10
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'

# Install kafka and create needed topics. 
  kafka:
    image: debezium/kafka:0.10 
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250
  debezium-connect:
    image: debezium/connect:0.10
    ports:
      - '8083:8083'
    links:
      - kafka
      - postgres  
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_config
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_status
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
