version: '2.1'

services:

  # Install zookeeper. 
  zookeeper:
    image: debezium/zookeeper:0.10
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'

# Install kafka and create needed topics. 
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      - LOG_DIR="/tmp/logs"
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250